# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11
language: swift

branches:
  only:
  - master

podfile: Example/Podfile

script:
- gem install cocoapods
- pod install --project-directory=Example
- set -o pipefail && xcodebuild \
    -enableCodeCoverage YES \
    -workspace Example/Convenience.xcworkspace \
    -scheme Convenience-Example \
    -sdk iphonesimulator13.0 \
    ONLY_ACTIVE_ARCH=NO
    clean test | xcpretty
- pod lib lint --verbose --allow-warnings
