# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11
language: swift

branches:
  only:
  - master

podfile: Example/Podfile

script:
- gem install cocoapods
- pod install --project-directory=Example
- chmod +x .xcodebuild.tests.sh
- ./.xcodebuild.tests.sh
- pod lib lint --allow-warnings
